import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import ProtectedRoute from '@/components/ProtectedRoute';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Tío Egoz - Admin',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ProtectedRoute>
					<div className='flex mx-auto max-w-7xl items-center justify-center gap-4 py-8'>
						<Image
							src='/logo.webp'
							alt='El tío Egoz - Admin'
							width={60}
							height={60}
							className='rounded-full'
						/>
						<h1 className='text-heading text-4xl font-bold'>
							El tío Egoz - Admin
						</h1>
					</div>
					{children}
				</ProtectedRoute>
			</body>
		</html>
	);
}
